version: "3"
services:
  converter:
    build:
      context: ./converter
      dockerfile: ../.docker/Dockerfile
    depends_on:
      - db
      - session_manager
    ports:
      - "8080:8080"
  session_manager:
    build:
      context: ./session_manager
      dockerfile: ../.docker/Dockerfile
    ports:
      - "8081:8080"
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: ${DB_USER:-demo}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-nopassword}
      POSTGRES_DB: ${DB_NAME:-demo}
    ports:
      - "5432:5432"
    volumes:
      - numbers-postgresql:/var/lib/postgresql
volumes:
  numbers-postgresql: {}
